parameters:
    cours_images_directory: '%kernel.project_dir%/public/assets/img'
    edenai_api_key: '%env(EDENAI_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Knp\Snappy\Pdf:
        arguments:
            $binary: '"C:/Program Files/wkhtmltopdf/bin/wkhtmltopdf.exe"'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
